#!/usr/bin/env bash

# spbk-assemble  -  simple disk image creator for sparsebak archives
# Christopher Laprise, tasket@github.com


set -e

if [ -n "$1" ] & [ -d "$1" ]; then
  voldir="$1"
  volname=`basename $voldir`
else
  echo "Usage: spbk-assemble <path-to-volume-dir>"
  exit 1
fi

( cd "$voldir"
  curdir=`pwd`
  rm -rf full || true
  mkdir full

  echo
  echo "Getting metadata for sparsebak volume $volname."

  sessions=`find . -name 'S_*' -type d -exec basename '{}' \; |sort --reverse`
  read last therest <<<$sessions
  read one two volsize <<<`grep '^volsize =' $last/info`
  read one two chunksize <<<`grep '^chunksize =' $last/info`

  echo -n "Creating links for sessions:"
  for s in $sessions; do
    echo -n " $s"
    cp -rln $s/* full
  done
  echo -n "..."
  dd if=/dev/zero of=full/zero bs=$chunksize count=1  2>/dev/null
  find full -size 0 -type f -exec ln -srf full/zero '{}' \;
  echo

  echo
  echo -n "Calculating SHA256 hash..."
  sha=`find full -name 'x*' | sort | xargs zcat -f | sha256sum`
  echo
  echo $sha

  echo
  echo "Volume instance located in $voldir/full dir."
  echo "To make disk image, use:"
  echo "\$ cd $voldir"
  echo "\$ find full -name 'x*' | sort | xargs zcat -f | dd of=file.img conv=sparse"
)

echo
echo "Done."
